# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93af49be07f5ab572050bb76437da406323cb512536e4869a1d320fc83860625db27bcab7d56c70d266f6752d2f7f529b1916d8f960a03ef19c0a4aaf080b1aa

test:
  secret_key_base: 948c73324f2c2f8c8b02f3ab9206f90a1a7f500e1b45630f7cb018c1de4ff8f55487512ed7cbb41ebc05777e724cb22b3529da17c6bba85194250e5683478e1e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
