# Categories
category_list = [
		{:name=>"Academia"},
		{:name=>"Advertising"},
		{:name=>"Animation"},
		{:name=>"Architecture"},
		{:name=>"Art Direction"},
		{:name=>"Automotive Design"},
		{:name=>"Blogging"},
		{:name=>"Branding"},
		{:name=>"Calligraphy"},
		{:name=>"Caricature"},
		{:name=>"Carpentry"},
		{:name=>"Cartooning"},
		{:name=>"Ceramics"},
		{:name=>"Character Design"},
		{:name=>"Choreography"},
		{:name=>"Cinematography"},
		{:name=>"Claymation"},
		{:name=>"Comedy"},
		{:name=>"Computer Animation"},
		{:name=>"Confectionary Arts"},
		{:name=>"Consulting"},
		{:name=>"Copywriting"},
		{:name=>"Costume Design"},
		{:name=>"Crafts"},
		{:name=>"Creative Direction"},
		{:name=>"Culinary Alchemy"},
		{:name=>"Culinary Arts"},
		{:name=>"Dance"},
		{:name=>"Design"},
		{:name=>"Digital Art"},
		{:name=>"Digital Imaging"},
		{:name=>"Digital Photography"},
		{:name=>"Directing"},
		{:name=>"DJing"},
		{:name=>"Documentary"},
		{:name=>"Drawing"},
		{:name=>"Editing"},
		{:name=>"Editorial Design"},
		{:name=>"Engineering"},
		{:name=>"Enology (Wines)"},
		{:name=>"Entrepreneurship"},
		{:name=>"Exhibition Design"},
		{:name=>"Fashion"},
		{:name=>"Fashion Styling"},
		{:name=>"Film"},
		{:name=>"Fine Arts"},
		{:name=>"Furniture Design"},
		{:name=>"Game Design"},
		{:name=>"Glass Blowing"},
		{:name=>"Graffiti"},
		{:name=>"Graphic Design"},
		{:name=>"Hair Styling"},
		{:name=>"Ice Sculpting"},
		{:name=>"Icon Design"},
		{:name=>"Illustration"},
		{:name=>"Industrial Design"},
		{:name=>"Information Architecture"},
		{:name=>"Installation Design"},
		{:name=>"Interaction Design"},
		{:name=>"Interior Design"},
		{:name=>"Jewelry Design"},
		{:name=>"Journalism"},
		{:name=>"Landscape Design"},
		{:name=>"Leather Working"},
		{:name=>"Lighting Design"},
		{:name=>"Machinima"},
		{:name=>"Magic"},
		{:name=>"MakeUp Arts (MUA)"},
		{:name=>"Marketing"},
		{:name=>"Masonry"},
		{:name=>"Metal Working"},
		{:name=>"Millinery"},
		{:name=>"Motion Graphics"},
		{:name=>"Multimedia"},
		{:name=>"Music"},
		{:name=>"Music Composition"},
		{:name=>"Music Production"},
		{:name=>"Origami"},
		{:name=>"Packaging"},
		{:name=>"Painting"},
		{:name=>"Pattern Design"},
		{:name=>"Performing Arts"},
		{:name=>"Perfumery"},
		{:name=>"Philanthropy"},
		{:name=>"Philosophy"},
		{:name=>"Photo Illustration"},
		{:name=>"Photo Manipulation"},
		{:name=>"Photography"},
		{:name=>"Photojournalism"},
		{:name=>"Playwriting"},
		{:name=>"Podcasting"},
		{:name=>"Poetry"},
		{:name=>"Print Design"},
		{:name=>"Product Design"},
		{:name=>"Production"},
		{:name=>"Programming"},
		{:name=>"Publishing"},
		{:name=>"Puppetry"},
		{:name=>"Retouching"},
		{:name=>"Screenwriting"},
		{:name=>"Sculpting"},
		{:name=>"Set Design"},
		{:name=>"Singing"},
		{:name=>"Software Architecture"},
		{:name=>"Songwriting"},
		{:name=>"Sound Design"},
		{:name=>"Storyboarding"},
		{:name=>"Storytelling"},
		{:name=>"Street Art"},
		{:name=>"Television"},
		{:name=>"Textile Design"},
		{:name=>"Theater"},
		{:name=>"Toy Design"},
		{:name=>"Typography"},
		{:name=>"Urbanism"},
		{:name=>"User Interface Design"},
		{:name=>"Video Arts"},
		{:name=>"Video Blogging"},
		{:name=>"Video Game Design"},
		{:name=>"Video Jockey"},
		{:name=>"Virtual World Design"},
		{:name=>"Visual Arts"},
		{:name=>"Visual Effects"},
		{:name=>"Web Design"},
		{:name=>"Web Development"},
		{:name=>"Wood Working"},
		{:name=>"Writing"}
]

category_list.each do |category|
	Category.create!(name: category[:name])
end


# Licenses
license = License.create!(name: 'MIT License',
                          description: 'Open Sourced, Free to Use')

# Users
user = User.create!(email: 'sahil.gadimbay@gmail.com',
                    password: '123456',
                    password_confirmation: '123456',
                    username: 'gadimbayli',
                    first_name: 'Sahil',
                    last_name: 'Gadimbayli')

User.create!(email: 'gadimbayli@gmail.com',
             password: '123456',
             password_confirmation: '123456',
             first_name: 'Tom',
             username: 'gadimbayli2',
             last_name: 'Johnes')

# Creations
Creation.create!(user: user,
                 title: 'lorem ipsum lorem ipsum',
                 content: 'some random content',
                 license_id: license,
                 category: Category.first,
                 published: true)


# Payment Methods
credit_cart = PaymentMethod.create!(name: 'Credit Cart',
                                    shorthand: 'cc')
paypal = PaymentMethod.create!(name: 'PayPal',
                               shorthand: 'paypal')
